[project]
name = "colrev.critical_review"
description = "CoLRev package for critical reviews"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "stable"
review_type = "colrev.packages.critical_review.src.critical_review:CriticalReview"
