[project]
name = "colrev.methodological_review"
description = "CoLRev package for methodological reviews"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "experimental"
review_type = "colrev.packages.methodological_review.src.methodological_review:MethodologicalReview"
