[project]
name = "colrev.profile"
description = "CoLRev package for creating profiles"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "experimental"
data = "colrev.packages.profile.src.profile:Profile"
